# Generated by Django 3.0.5 on 2020-04-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('cnt_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_name', models.CharField(max_length=50)),
                ('from_email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField(max_length=1150)),
            ],
        ),
    ]
