# Generated by Django 3.0.5 on 2020-04-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('arval_date', models.CharField(default=None, max_length=40)),
                ('dep_date', models.CharField(default=None, max_length=40)),
                ('customer_name', models.CharField(default=None, max_length=40)),
                ('persons', models.CharField(default=None, max_length=40)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('room_type', models.CharField(default=None, max_length=40)),
                ('phone_num', models.CharField(default=None, max_length=40)),
                ('price', models.CharField(default=None, max_length=40)),
            ],
        ),
    ]
